services:

  redis:
    container_name: "redis"
    image: redis:latest
    ports:
      - "6379:6379"

  waffle-bot:
    container_name: "waffle-bot"
    image: waffle-bot:latest
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - ./env/waffle-local.env
      - ./env/waffle-test-workspace.env
      - ./env/waffle-tier2.env
